### ISSUE TITLE
Extra oxeia in U+03D7 GREEK KAI SYMBOL

### ISSUE THREAD

**Issue by dscorbett** [agarick/autonoe#1]
The glyph for U+03D7 GREEK KAI SYMBOL should not include a diacritic above it.

**Comment by blobject** [comment]
Hi, thanks for the issue. But I don't think I'll fix this or work on autonoe much further.

Two reasons:
- This was a very brief curiosity project and consisted solely of tweaking the style of the existing "misc fixed 7x14b" font. And by "style", I mean at most something like making a 1-pixel stroke 2-pixels. I don't use autonoe for anything and doubt many others would either.
- This particular issue also exists in the original 7x14b font.
  - I'm not sure who exactly contributed this glyph, but the font file (and also the AUTHORS file) can be downloaded from https://www.cl.cam.ac.uk/~mgk25/ucs-fonts.html (under "Download" > `ucs-fonts.tar.gz` > `7x14B.bdf`).

**Comment by blobject** [comment]
Closing as wont-fix. Please see/contact upstream project.
